# Generated by Django 6.1.1 on 2026-09-25 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_job_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('communication', 'Communication & Marketing'), ('documents', 'Documents & eSignature'), ('ai', 'AI & Smart Automation'), ('contacts', 'Contacts & Engagement'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured services appear as large showcase blocks at the top.'),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
