# Generated by Django 6.1.1 on 2026-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_service_category_service_is_featured_servicefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend Engineer'), ('backend', 'Backend Engineer'), ('software', 'Software Engineer'), ('ai', 'AI Engineer')], default='software', max_length=20),
        ),
    ]
