# Generated by Django 6.1.1 on 2026-09-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_teammember_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, upload_to='team/'),
        ),
    ]
