# Generated by Django 6.1.1 on 2026-09-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_teammember_photo_url_teammember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
