# Generated by Django 6.1.1 on 2026-09-25 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_teammember_is_featured_teammember_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin',
        ),
        migrations.CreateModel(
            name='MemberSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('email', 'Email (Gmail)'), ('github', 'GitHub'), ('x', 'X (Twitter)'), ('website', 'Website / Portfolio'), ('other', 'Other')], default='linkedin', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='website.teammember')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
