# Generated by Django 6.1.1 on 2026-09-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_teammember_linkedin_membersocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='leadership',
            field=models.CharField(blank=True, choices=[('', 'None'), ('overall', 'Overall Team Lead'), ('frontend', 'Frontend Team Lead'), ('backend', 'Backend Team Lead')], default='', max_length=20),
        ),
    ]
