# Generated by Django 6.1.1 on 2026-09-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_teammember_leadership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='is_featured',
        ),
    ]
